import type { Metadata } from 'next';

import { ThemeProvider } from 'next-themes';
import './globals.css';

import { NextIntlClientProvider } from 'next-intl';
import { Geist_Mono, JetBrains_Mono } from 'next/font/google';
const geist_mono = Geist_Mono({
  subsets: ['latin'],
  weight: ['600'],
  variable: '--display-family',
});
const jetbrains_mono = JetBrains_Mono({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--body-family',
});
const jetbrains_mono_mono = JetBrains_Mono({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning
    >
      <body className={`${geist_mono.variable} ${jetbrains_mono.variable} ${jetbrains_mono_mono.variable}`}>
        <NextIntlClientProvider>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
